---
- name: SETUP
  hosts: node0
  become: true

  tasks:
    - name: INSTALL PACKAGE
      apt: name={{item}} update_cache=yes state=latest
      with_items:
        - build-essential
        - npm
        - nodejs-legacy
        - git

    - name: INSTALL FOREVER
      npm: name=forever global=yes state=latest

    - name: GIT CLONE
      git: 
        repo: https://github.com/CSC-DevOps/App.git
        dest: "/home/vagrant/App"
      register: git_cloned
      
    - name: Install NPM Packages
      npm:
        path: "/home/vagrant/App"